Repository imhaeunk/Team_mini, pull requests merged in 2021-11, with the labels that each got.

#29 [Login component] Set to login process
  src/components/HomeHeader.vue
  src/components/SignIn.vue
  src/index.html
  src/main.js
  src/routes/Certification.vue
  src/routes/Home.vue
  src/routes/guards.js
  src/store/admin.js
  src/store/index.js
  src/store/user.js
  src/utils/authenticationApiConfig.js
Labels: enhancement

#34 [기본 스타일 셋팅] base, constants, mixins, modules
  src/scss/_variables.scss
  src/scss/base/_normalize.scss
  src/scss/base/_reset.scss
  src/scss/constants/_colors.scss
  src/scss/constants/_typography.scss
  src/scss/main.scss
  src/scss/mixins/_flexbox.scss
  src/scss/mixins/_positions.scss
  src/scss/mixins/_text-style.scss
  src/scss/modules/_buttons.scss
  src/scss/modules/_forms.scss
Labels: enhancement

#50 [제품 검색 결과 리팩토링 및 추천 키워드 화면 구성]
  src/components/KeywordList.vue
  src/components/SearchResults.vue
  src/routes/Home.vue
  src/store/user.js
  src/utils/gucciImage.js
  src/utils/louboutinImage.js
  src/utils/theRowImage.js
  src/utils/valentinoImage.js
  src/utils/votegaImage.js
Labels: enhancement

#59 SingleProductDetails 에서 User, Admin 용 2가지 컴포넌트로 분기 완료.
  src/components/AdminSingleProductDetails.vue
  src/components/AllProductsList.vue
  src/components/SearchResults.vue
  src/components/UserSingleProductDetails.vue
  src/index.html
  src/routes/index.js
Labels: enhancement

#62 docs: 관리자 페이지에서 제품 상세보기 레이아웃 설정 완료
  src/components/AdminSingleProductDetails.vue
Labels: documentation, enhancement

#73 전체 계좌 리스트 목록 디자인 완료
  src/components/AccountList.vue
  src/components/AccountListChangeCheck.vue
  src/components/AccountRemove.vue
  src/components/MyAccount.vue
  src/components/PurchaseItem.vue
  src/routes/AddAccount.vue
Labels: enhancement

#82 docs: 계좌 해지하기 모달창 버그 이슈 해결
  src/components/AccountList.vue
  src/components/AccountRemove.vue
  src/components/SingleProductDetails.vue
  src/store/user.js
Labels: bug
